// Generated by scripts/screens.mjs. Do not edit by hand.
//
// Filenames carry a hash of their contents so that `/screens/*` can stay
// immutable in the cache: new artwork is always a new URL. Re-run
// `node scripts/screens.mjs` after the app's marketing captures change.

export type Screen = { light: string; dark: string };

export const screens = {
  welcome: {
    light: "/screens/welcome-47282008.webp",
    dark: "/screens/welcome-dark-27e6754a.webp",
  },
  home: {
    light: "/screens/home-51413e45.webp",
    dark: "/screens/home-dark-2d3e4a5f.webp",
  },
  manage: {
    light: "/screens/manage-edd5e566.webp",
    dark: "/screens/manage-dark-7099aaef.webp",
  },
  recovery: {
    light: "/screens/recovery-fd3dde23.webp",
    dark: "/screens/recovery-dark-7649c1b0.webp",
  },
  community: {
    light: "/screens/community-aa7eb131.webp",
    dark: "/screens/community-dark-b54937e3.webp",
  },
} as const satisfies Record<string, Screen>;
