// Generated by scripts/screens.mjs. Do not edit by hand.
//
// Filenames carry a hash of their contents so that `/screens/*` can stay
// immutable in the cache: new artwork is always a new URL. Re-run
// `node scripts/screens.mjs` after the app's marketing captures change.

export type Screen = { light: string; dark: string };

export const screens = {
  welcome: {
    light: "/screens/welcome-d688ddc5.webp",
    dark: "/screens/welcome-dark-aee1742a.webp",
  },
  home: {
    light: "/screens/home-4772b11b.webp",
    dark: "/screens/home-dark-0cbf31f9.webp",
  },
  manage: {
    light: "/screens/manage-1475d766.webp",
    dark: "/screens/manage-dark-3eb4edc7.webp",
  },
  recovery: {
    light: "/screens/recovery-3d66373f.webp",
    dark: "/screens/recovery-dark-f2733534.webp",
  },
  community: {
    light: "/screens/community-5deb35a4.webp",
    dark: "/screens/community-dark-24f001a8.webp",
  },
} as const satisfies Record<string, Screen>;
