// Rebuilds the product screenshots from the app repository.
//
// Usage: node scripts/screens.mjs [path-to-parkiwell/marketing/raw]
//
// The app is the source of truth for what the product looks like, so the
// screenshots here are generated from its captures rather than edited by hand.
// Re-run this after the app's marketing captures change.
//
// Filenames carry a hash of their own contents. `/screens/*` is served
// immutable for a year, so a screenshot that changed under a filename that did
// not would keep showing the old picture to everyone who had already visited.
// Hashing means new artwork is always a new URL, and the caching stays honest.
import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const SOURCE =
  process.argv[2] ??
  path.join(process.cwd(), "..", "ParkiWell", "marketing", "raw");
const OUT = path.join(process.cwd(), "public", "screens");
const MANIFEST = path.join(process.cwd(), "src", "lib", "screens.ts");

// Rendered at 336 CSS pixels at most, so 680 wide covers two device pixels.
const WIDTH = 680;
const QUALITY = 82;

const shots = [
  { name: "welcome", light: "01-onboarding", dark: "10-onboarding-dark" },
  { name: "home", light: "02-home", dark: "05-home-dark" },
  { name: "manage", light: "03-manage", dark: "07-manage-dark" },
  { name: "recovery", light: "04-recovery", dark: "08-recovery-dark" },
  { name: "community", light: "06-community", dark: "09-community-dark" },
];

// The app repository has changed the format of its captures before, so match
// on the name and take whichever extension is actually there.
async function resolve(base) {
  const wanted = base.replace(/\.[^.]+$/, "");
  const files = await readdir(SOURCE);
  const found = files.find((file) => file.replace(/\.[^.]+$/, "") === wanted);
  if (!found) {
    throw new Error(
      `no capture named "${wanted}" in ${SOURCE}. Found: ${files.join(", ")}`,
    );
  }
  return path.join(SOURCE, found);
}

async function encode(sourceFile, name) {
  const buffer = await sharp(await resolve(sourceFile))
    .resize({ width: WIDTH })
    .webp({ quality: QUALITY, effort: 6 })
    .toBuffer();
  const hash = createHash("sha256").update(buffer).digest("hex").slice(0, 8);
  const file = `${name}-${hash}.webp`;
  await writeFile(path.join(OUT, file), buffer);
  return { file, bytes: buffer.length };
}

await mkdir(OUT, { recursive: true });

const built = [];
for (const shot of shots) {
  const light = await encode(shot.light, shot.name);
  const dark = await encode(shot.dark, `${shot.name}-dark`);
  built.push({ name: shot.name, light: light.file, dark: dark.file });
  const kb = (n) => `${(n / 1024).toFixed(1)} kB`;
  console.log(
    `${shot.name.padEnd(10)} ${light.file.padEnd(24)} ${kb(light.bytes).padStart(9)}   ` +
      `${dark.file.padEnd(29)} ${kb(dark.bytes).padStart(9)}`,
  );
}

// Anything left over is a screenshot from a previous run.
const keep = new Set(built.flatMap((shot) => [shot.light, shot.dark]));
for (const file of await readdir(OUT)) {
  if (!keep.has(file)) {
    await rm(path.join(OUT, file));
    console.log(`removed stale ${file}`);
  }
}

const manifest = `// Generated by scripts/screens.mjs. Do not edit by hand.
//
// Filenames carry a hash of their contents so that \`/screens/*\` can stay
// immutable in the cache: new artwork is always a new URL. Re-run
// \`node scripts/screens.mjs\` after the app's marketing captures change.

export type Screen = { light: string; dark: string };

export const screens = {
${built
  .map(
    (shot) =>
      `  ${shot.name}: {\n` +
      `    light: "/screens/${shot.light}",\n` +
      `    dark: "/screens/${shot.dark}",\n` +
      `  },`,
  )
  .join("\n")}
} as const satisfies Record<string, Screen>;
`;

await writeFile(MANIFEST, manifest);
console.log(`\nwrote ${path.relative(process.cwd(), MANIFEST)}`);

// The README shows four of these, and the filenames it points at change every
// time this runs. Rewriting the block here means the pictures in the README
// cannot rot into broken images the next time the app's captures change.
const README = path.join(process.cwd(), "README.md");
const shown = [
  ["home", "light", "Home: your whole day at a glance"],
  ["manage", "light", "Manage: medications and doses"],
  ["recovery", "light", "Recovery: practice with a plan"],
  ["community", "dark", "Community, in dark mode"],
];
const row =
  `<!-- screens:start -->\n<p align="center">\n` +
  shown
    .map(([name, theme, alt]) => {
      const shot = built.find((item) => item.name === name);
      return `  <img src="/screens/${theme === "dark" ? shot.dark : shot.light}" alt="${alt}" width="22%">`;
    })
    .join("\n")
    .replaceAll('src="/screens/', 'src="public/screens/') +
  `\n</p>\n<!-- screens:end -->`;

const readme = await readFile(README, "utf8");
const replaced = readme.replace(
  /<!-- screens:start -->[\s\S]*?<!-- screens:end -->/,
  row,
);
if (replaced !== readme) {
  await writeFile(README, replaced);
  console.log("updated the screenshot row in README.md");
}

// Every screenshot has to keep the phone frame's aspect ratio, or the frame
// crops it.
const { width, height } = await sharp(
  path.join(OUT, built[0].light),
).metadata();
console.log(`aspect ${width}x${height} (${(width / height).toFixed(4)})`);
